### ISSUE TITLE
Add in ci/cd

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/dotfiles#48]
## TODO
- [ ] Add in Github Actions to generate build packages per profile for:
  - [ ] Work (core + work profiles)
  - [ ] Personal (core + dev + personal profiles)

**Comment by JasonYao** [comment]
Added in 8471a64a979907336a613612a925323ac9800836
